# Generated by Django 5.1.6 on 2025-04-09 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotify_app', '0002_comment_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='album_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
